apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-name
  labels:
    name: my-name
spec:
  replicas: 100
  selector:
    matchLabels:
      app: formatier/gateway-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: gateway-server
    spec:
      containers:
        - image: formatier/gateway-server
          name: gateway-server
          resources:
            requests:
              cpu: "20m"
              memory: "32M"
            limits:
              cpu: "100m"
              memory: "128M"
          livenessProbe:
            httpGet:
              path: /status/health
              port: 5000
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /status/health
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          env:
            - name: ENVVARNAME
              value: ENVVARVALUE
          ports:
            - containerPort: 5000
              name: my-name
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always
