name: publish
on: [push]
jobs:
  push_docker_image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python deployments/scripts/github/build_images.py